name: 📄✨ Build & Deploy CV to GitHub Pages

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: 🛠️ Checkout Repository
        uses: actions/checkout@v4

      - name: Install minimal TeX deps
        run: |
          sudo apt-get update
          sudo apt-get install -y \
          fonts-font-awesome \
          texlive-fonts-extra

      - name: 🚀 Setup Tectonic
        uses: wtfjoke/setup-tectonic@v4
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          tectonic-version: "0.15.0"

      - name: 🏗️ Build PDF
        run: |
          tectonic -X build

      - name: 📦 Prepare Pages Artifact
        run: |
          mkdir -p public
          cp build/AliMafi/AliMafi.pdf public/index.pdf

      - name: 📄 Upload Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: public

  deploy:
    needs: build
    runs-on: ubuntu-latest

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: 🚀 Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
